### PR TITLE
enable signature-help on java language server

### PR DESCRIPTION
**Pull request by appelgriebsch**
update jdtls to latest version (for feature and speed improvements) as well as set flag to enable signature help functionality

### CODE REVIEW

**Comment by 50Wliu** [comment]
Sorry for dropping the ball on the last one @appelgriebsch - will try to review this one better!

**Comment by 50Wliu** [comment]
Looks like 0.39.0 got released today with what seems like a pretty important NPE fix - would you mind updating to that?

**Comment by appelgriebsch** [comment]
Looks like it hasn't been publicly released yet... https://github.com/eclipse/eclipse.jdt.ls/releases

**Comment by 50Wliu** [comment]
@Aerijo maybe you can help here given your work with the IDE packages - I'm noticing that signature help isn't showing unless I manually call `signature-help:show`, even though I have it set to track on type (`atom-ide-signature-help`). Seems like there's something about trigger characters? Is that handled by ide-java or the language server?

Also, this PR adds a new consumed service for signature help, but doesn't define `consumeSignatureHelp` anywhere - do we need to? If we don't have that function, do we even need to declare that we're consuming it?

**Comment by Aerijo** [comment]
The [server declares](https://microsoft.github.io/language-server-protocol/specification) characters meant to automatically trigger a signature
```
/**
 * Signature help options.
 */
export interface SignatureHelpOptions {
	/**
	 * The characters that trigger signature help
	 * automatically.
	 */
	triggerCharacters?: string[];
}
```

I'm not familiar with signature handling, but `atom-languageclient` [appears to recognise](https://github.com/atom/atom-languageclient/blob/3f44ceb9b8b8174fa115e5e32c14e773471d5c34/lib/adapters/signature-help-adapter.ts#L44-L47) them. It also has a definition for `consumeSignatureHelp`, so that shouldn't be an issue (this package still needs to consume `signature-help` directly like it is in the PR). The signatures (sub)package opf `atom-ide-ui` is responsible for triggering based on characters, and far as I can tell it support trigger characters fine.

So you'll have to see if the server is actually sending trigger characters to see if there's a problem. I do this by adding console logs with the messages somewhere in the `vscode-jsonrpc` node module I think.

**Comment by appelgriebsch** [comment]
Looks like the java language server only delivers the opening brace as trigger character....

image

At least in my tests this is properly recognised...

image

On the other hand I would expect to have the comma as trigger character as well, so that it will update as soon as I jump through the list of parameters

**Comment by 50Wliu** [comment]
Hmm...here's what I'm seeing:
java-no-automatic-signature-help

Maybe that's an issue with the signature help package though, and not this one + the server?

**Comment by appelgriebsch** [comment]
This might be an issue with atom-ide-signature-help that happens sporadically if the file is opened when starting the editor. If you close the initial text window and open it via the project tree it will work as expected....

**Comment by appelgriebsch** [comment]
@50Wliu: is there still something missing? (little reminder to merge the PR ;))

**Comment by 50Wliu** [comment]
I think the 100% bug is something we can live with in exchange for all these changes since the last update, especially signature help :). I'll file a follow-up issue so we can track that bug.

**Comment by 50Wliu** [comment]
Thanks @appelgriebsch!

**Pull request merged**
